# Site settings
title: 窗外蟋蟀
SEOTitle: 窗外蟋蟀的博客 | Keysaim Blog
header-img: img/home-bg-hill.jpg
email: keysaim@gmail.com
description: "描述"
keyword: "窗外蟋蟀, keysaim, cdn, docker, go, golang, python, C/C++, 流媒体, 分发网络, 音视频, 编解码"
url: "https://keysaim.github.io"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'



# SNS settings
RSS: false
#weibo_username:     keysaim
zhihu_username:     keysaim
github_username:    keysaim
#twitter_username:   keysaim
jianshu_username:   e413b88a622b
#facebook_username:  keysaim
# linkedin_username:  firstname-lastname-idxxxx



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
#markdown: redcarpet
#redcarpet:
    #extensions: ["tables", "fenced_code_blocks"]



# Disqus settings
#disqus_username: keysaim

# Netease setttings
netease_comment: false

# For gitment
gitment: true
gitment-repo: comments
gitment-client-id: 8d920ad685683a529e83
gitment-client-secret: ffabf134048e374883ee67d3786a9a6b7d8d3cdc

# For test
#gitment-repo: test-comments
#gitment-client-id: 3687ee49c8a69a86e75e
#gitment-client-secret: 53604cc6e16fe16160b36be7d2f379e46994b728


# Analytics settings
# Baidu Analytics 
# ba_track_id: [your track id]

# Google Analytics
ga_track_id: 'UA-104622100-1'
ga_domain: keysaim.github.io



# Sidebar settings
sidebar: false                           # whether or not using Sidebar.
sidebar-about-description: "边栏描述"
# TODO need add the headshot
sidebar-avatar: /img/avatar-.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
#friends: []

anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`
anchorjs-visible: hover
anchorjs-icon: §
anchorjs-placement: right

